version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  api:
#    build: .
#    command: ["./main"]
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      DB_HOST: db
#    volumes:
#      - ./cmd/api:/app/cmd/api

volumes:
  postgres-data:
